server:
    port: 8088
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/rest_with_spring_boot_and_kotlin_destination_ms?useTimezone=true&serverTimezone=UTC
        username: root
        password: password
    flyway:
        url: jdbc:mysql://localhost:3307/rest_with_spring_boot_and_kotlin_destination_ms?useTimezone=true&serverTimezone=UTC
        user: root
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: false
    kafka:
        bootstrap-servers: "localhost:9092"
        consumer:
            group-id: "person.group-id"
            topic: "PERSON.CONSUMER.TOPIC"
            auto-offset-reset: "earliest"
        producer:
            topic: "PERSON.CONSUMER.TOPIC.RESPONSE"